{"metadata":{"role":"symbol","externalID":"c:@M@UltraliteSDK@objc(cs)Ultralite(im)encodeWithCoder:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"title":"encodeWithCoder:","modules":[{"name":"UltraliteSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encodeWithCoder:"}],"symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/encodeWithCoder:"},"variants":[{"paths":["\/documentation\/ultralitesdk\/ultralite\/encodewithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Encodes the receiver using a given archiver.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"encodeWithCoder:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}],"platforms":["watchOS"],"languages":["occ"]}],"kind":"declarations"},{"parameters":[{"name":"coder","content":[{"type":"paragraph","inlineContent":[{"text":"An archiver object","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite"]]},"sections":[],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","title":"UltraliteSDK","abstract":[{"text":"Use this SDK to easily send text and images to your Vuxix smart glasses.","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/ultralitesdk"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite":{"navigatorTitle":[{"kind":"identifier","text":"Ultralite"}],"title":"Ultralite","kind":"symbol","role":"symbol","abstract":[{"text":"Use this object to communicate with the glasses.  Handles all the communication to the BLE stack. Does all the protocol and encypting and decrypting of payloads.","type":"text"}],"url":"\/documentation\/ultralitesdk\/ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Ultralite"}],"type":"topic"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/encodeWithCoder:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encodeWithCoder:"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"encodeWithCoder:","kind":"identifier"}],"title":"encodeWithCoder:","abstract":[{"type":"text","text":"Encodes the receiver using a given archiver."}],"url":"\/documentation\/ultralitesdk\/ultralite\/encodewithcoder:","type":"topic","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/encodeWithCoder:"}},"variantOverrides":[{"patch":[{"value":"Ultralite","op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/title"},{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/fragments","value":[{"text":"Ultralite","kind":"identifier"}],"op":"replace"},{"value":[{"text":"Ultralite","kind":"identifier"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}