{"abstract":[{"text":"Requests the specified layout, timeout and hidden status bar if desired.  Optionally configures taps and auto release after timeout.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestControl"},{"text":"(","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Ultralite","kind":"typeIdentifier","preciseIdentifier":"c:@M@UltraliteSDK@objc(cs)Ultralite"},{"kind":"text","text":"."},{"text":"Layout","kind":"typeIdentifier","preciseIdentifier":"s:12UltraliteSDK0A0C6LayoutO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeout"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"hideStatusBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showTapAnimation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"maxNumTaps","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"autoReleaseControlOnDisplayTimeout","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"UltraliteSDK"}],"externalID":"s:12UltraliteSDK0A0C14requestControl6layout7timeout13hideStatusBar16showTapAnimation10maxNumTaps011autoReleaseD16OnDisplayTimeoutSbAC6LayoutO_SiS2bSiSbtF","title":"requestControl(layout:timeout:hideStatusBar:showTapAnimation:maxNumTaps:autoReleaseControlOnDisplayTimeout:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestControl","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@UltraliteSDK@objc(cs)Ultralite","kind":"typeIdentifier","text":"Ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:12UltraliteSDK0A0C6LayoutO","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Layout","text":"Layout"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"hideStatusBar","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"showTapAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"maxNumTaps"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" = 0, "},{"text":"autoReleaseControlOnDisplayTimeout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["watchOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"layout","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An Ultralite.Layout"}]}]},{"name":"timeout","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A timeout value in seconds.  Use zero to keep the display on forever. (must be greater than or equal to zero)"}]}]},{"name":"autoReleaseControlOnDisplayTimeout","content":[{"inlineContent":[{"type":"text","text":"OPTIONAL: will automatically release control when the display timeout is hit.  Creates a quick view of information."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also customize the tap behavior. A max number of taps between 0-3 can be specified. Any other value will be treated like zero. Based on this value, the following behavior will be present:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0 - No taps are reported. (default)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"1 - Only single taps are reported. This has the shortest delay from when the user taps until processing.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"2 - Single and double taps are reported. This has a medium delay from when the user taps until processing.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"3 - Single, double, and triple taps are reported. This has the longest delay from when the user taps until processing."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Picking the lowest number of taps needed will improve overall reponse time."}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"If not connected to glasses, this method call does nothing.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"parameter hideStatusBar :OPTIONAL:  true to hide the status bar, false to show it (true only applies to Ultralite.Layout.canvas layout).  Default value is false","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"parameter showTapAnimation :OPTIONAL:  whether the tap animation is shown on the glasses.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"parameter maxNumTaps :OPTIONAL: the max number of taps as described above"}]}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/ultralitesdk\/ultralite\/requestcontrol(layout:timeout:hidestatusbar:showtapanimation:maxnumtaps:autoreleasecontrolondisplaytimeout:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/requestControl(layout:timeout:hideStatusBar:showTapAnimation:maxNumTaps:autoReleaseControlOnDisplayTimeout:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite"]]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite":{"navigatorTitle":[{"kind":"identifier","text":"Ultralite"}],"title":"Ultralite","kind":"symbol","role":"symbol","abstract":[{"text":"Use this object to communicate with the glasses.  Handles all the communication to the BLE stack. Does all the protocol and encypting and decrypting of payloads.","type":"text"}],"url":"\/documentation\/ultralitesdk\/ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Ultralite"}],"type":"topic"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/requestControl(layout:timeout:hideStatusBar:showTapAnimation:maxNumTaps:autoReleaseControlOnDisplayTimeout:)":{"title":"requestControl(layout:timeout:hideStatusBar:showTapAnimation:maxNumTaps:autoReleaseControlOnDisplayTimeout:)","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/requestControl(layout:timeout:hideStatusBar:showTapAnimation:maxNumTaps:autoReleaseControlOnDisplayTimeout:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestControl"},{"kind":"text","text":"("},{"text":"layout","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Ultralite","preciseIdentifier":"c:@M@UltraliteSDK@objc(cs)Ultralite"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:12UltraliteSDK0A0C6LayoutO","text":"Layout"},{"kind":"text","text":", "},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"hideStatusBar","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"showTapAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"maxNumTaps","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoReleaseControlOnDisplayTimeout"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/ultralitesdk\/ultralite\/requestcontrol(layout:timeout:hidestatusbar:showtapanimation:maxnumtaps:autoreleasecontrolondisplaytimeout:)","type":"topic","abstract":[{"type":"text","text":"Requests the specified layout, timeout and hidden status bar if desired.  Optionally configures taps and auto release after timeout."}],"role":"symbol","kind":"symbol"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/Layout":{"abstract":[{"type":"text","text":"Supported layout types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Layout"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layout"}],"title":"Ultralite.Layout","kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Layout","url":"\/documentation\/ultralitesdk\/ultralite\/layout","type":"topic"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","title":"UltraliteSDK","abstract":[{"text":"Use this SDK to easily send text and images to your Vuxix smart glasses.","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/ultralitesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/title","value":"Ultralite","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/fragments","value":[{"text":"Ultralite","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/navigatorTitle","value":[{"kind":"identifier","text":"Ultralite"}]}]}]}