{"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite"]]},"metadata":{"symbolKind":"method","title":"setCustomFontForAllText(font:)","externalID":"s:12UltraliteSDK0A0C23setCustomFontForAllText4fontySo6UIFontCSg_tF","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCustomFontForAllText","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?)"}],"modules":[{"name":"UltraliteSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ultralitesdk\/ultralite\/setcustomfontforalltext(font:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/setCustomFontForAllText(font:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCustomFontForAllText"},{"text":"(","kind":"text"},{"text":"font","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/setCustomFontForAllText(font:)":{"url":"\/documentation\/ultralitesdk\/ultralite\/setcustomfontforalltext(font:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomFontForAllText","kind":"identifier"},{"kind":"text","text":"("},{"text":"font","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","title":"setCustomFontForAllText(font:)","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/setCustomFontForAllText(font:)"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite":{"url":"\/documentation\/ultralitesdk\/ultralite","title":"Ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","abstract":[{"type":"text","text":"Use this object to communicate with the glasses.  Handles all the communication to the BLE stack. Does all the protocol and encypting and decrypting of payloads."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Ultralite"}],"navigatorTitle":[{"kind":"identifier","text":"Ultralite"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Ultralite","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/fragments","value":[{"text":"Ultralite","kind":"identifier"}]},{"op":"replace","value":[{"text":"Ultralite","kind":"identifier"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/navigatorTitle"}]}]}