{"abstract":[{"text":"If your app is a UNUserNotificationCenterDelegate, you should call this method from your delegate, with an empty completionHandler({}).  If you don’t call this from your delegate then things may not work correctly when responding to notifications.","type":"text"}],"metadata":{"symbolKind":"method","modules":[{"name":"UltraliteSDK"}],"navigatorTitle":[{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","externalID":"c:@CM@UltraliteSDK@objc(cs)Ultralite(im)userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","extendedModule":"UltraliteSDK","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"withCompletionHandler","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/userNotificationCenter(_:didReceive:withCompletionHandler:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ultralitesdk\/ultralite\/usernotificationcenter(_:didreceive:withcompletionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralite\/usernotificationcenter(_:didreceive:withcompletionhandler:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"center"},{"kind":"text","text":": "},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"text":"withCompletionHandler","kind":"externalParam"},{"kind":"text","text":" "},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/UNUserNotificationCenterDelegate-Implementations"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"abstract":[{"text":"If your app is a UNUserNotificationCenterDelegate, you should call this method from your delegate, with an empty completionHandler({}).  If you don’t call this from your delegate then things may not work correctly when responding to notifications.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ultralitesdk\/ultralite\/usernotificationcenter(_:didreceive:withcompletionhandler:)","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/userNotificationCenter(_:didReceive:withCompletionHandler:)","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","role":"symbol"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite":{"navigatorTitle":[{"text":"Ultralite","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this object to communicate with the glasses.  Handles all the communication to the BLE stack. Does all the protocol and encypting and decrypting of payloads."}],"url":"\/documentation\/ultralitesdk\/ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","title":"Ultralite","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Ultralite"}],"kind":"symbol","role":"symbol"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","role":"collection","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","abstract":[{"text":"Use this SDK to easily send text and images to your Vuxix smart glasses.","type":"text"}],"kind":"symbol","type":"topic","title":"UltraliteSDK"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/UNUserNotificationCenterDelegate-Implementations":{"url":"\/documentation\/ultralitesdk\/ultralite\/unusernotificationcenterdelegate-implementations","kind":"article","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/UNUserNotificationCenterDelegate-Implementations","type":"topic","title":"UNUserNotificationCenterDelegate Implementations","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"userNotificationCenter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":" *) ","kind":"text"},{"text":"center","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveNotificationResponse:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier","text":"UNNotificationResponse"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["watchOS"]}]}},{"value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/title","op":"replace","value":"Ultralite"},{"value":[{"kind":"identifier","text":"Ultralite"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/fragments"},{"value":[{"text":"Ultralite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/navigatorTitle"}]}]}