{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Layout"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textBottomLeftAlign","kind":"identifier"}],"platforms":["watchOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Layout\/textBottomLeftAlign","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"textBottomLeftAlign"}],"symbolKind":"case","externalID":"s:12UltraliteSDK0A0C6LayoutO19textBottomLeftAlignyA2EmF","roleHeading":"Case","modules":[{"name":"UltraliteSDK"}],"title":"Ultralite.Layout.textBottomLeftAlign"},"variants":[{"paths":["\/documentation\/ultralitesdk\/ultralite\/layout\/textbottomleftalign"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Text will appear at the bottom of the display, left aligned."}],"sections":[],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/Layout":{"abstract":[{"type":"text","text":"Supported layout types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Layout"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Layout"}],"title":"Ultralite.Layout","kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Layout","url":"\/documentation\/ultralitesdk\/ultralite\/layout","type":"topic"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","title":"UltraliteSDK","abstract":[{"text":"Use this SDK to easily send text and images to your Vuxix smart glasses.","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/ultralitesdk"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite":{"navigatorTitle":[{"kind":"identifier","text":"Ultralite"}],"title":"Ultralite","kind":"symbol","role":"symbol","abstract":[{"text":"Use this object to communicate with the glasses.  Handles all the communication to the BLE stack. Does all the protocol and encypting and decrypting of payloads.","type":"text"}],"url":"\/documentation\/ultralitesdk\/ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Ultralite"}],"type":"topic"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/Layout/textBottomLeftAlign":{"abstract":[{"type":"text","text":"Text will appear at the bottom of the display, left aligned."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"textBottomLeftAlign"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Layout\/textBottomLeftAlign","title":"Ultralite.Layout.textBottomLeftAlign","url":"\/documentation\/ultralitesdk\/ultralite\/layout\/textbottomleftalign"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Ultralite","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/fragments","value":[{"kind":"identifier","text":"Ultralite"}]},{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/navigatorTitle","value":[{"kind":"identifier","text":"Ultralite"}],"op":"replace"}]}]}