{"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"]]},"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/numberOfSectionsInTableView:","interfaceLanguage":"occ"},"metadata":{"role":"symbol","symbolKind":"method","title":"numberOfSectionsInTableView:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"navigatorTitle":[{"text":"numberOfSectionsInTableView:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"UltraliteSDK"}],"externalID":"c:@CM@UltraliteSDK@objc(cs)UltralitePickerController(im)numberOfSectionsInTableView:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"numberOfSectionsInTableView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitepickercontroller\/numberofsectionsintableview:"]}],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UltralitePickerController"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller","abstract":[{"text":"Convience UIViewController that can easily be shown to user to have them select a pair of glasses to communicate with.","type":"text"}],"title":"UltralitePickerController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UltralitePickerController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController/numberOfSectionsInTableView:":{"abstract":[],"navigatorTitle":[{"text":"numberOfSectionsInTableView:","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/numberOfSectionsInTableView:","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller\/numberofsectionsintableview:","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"numberOfSectionsInTableView:","kind":"identifier"}],"title":"numberOfSectionsInTableView:"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"UltralitePickerController","op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/title"},{"value":[{"text":"UltralitePickerController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/fragments"},{"op":"replace","value":[{"text":"UltralitePickerController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}