{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/tableView:heightForHeaderInSection:"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitepickercontroller\/tableview:heightforheaderinsection:"]}],"metadata":{"roleHeading":"Instance Method","title":"tableView:heightForHeaderInSection:","navigatorTitle":[{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"role":"symbol","modules":[{"name":"UltraliteSDK"}],"externalID":"c:@CM@UltraliteSDK@objc(cs)UltralitePickerController(im)tableView:heightForHeaderInSection:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"heightForHeaderInSection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"section","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"]]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UltralitePickerController"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller","abstract":[{"text":"Convience UIViewController that can easily be shown to user to have them select a pair of glasses to communicate with.","type":"text"}],"title":"UltralitePickerController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UltralitePickerController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController/tableView:heightForHeaderInSection:":{"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/tableView:heightForHeaderInSection:","type":"topic","title":"tableView:heightForHeaderInSection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"kind":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller\/tableview:heightforheaderinsection:","role":"symbol","navigatorTitle":[{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"UltralitePickerController","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/title"},{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/fragments","value":[{"kind":"identifier","text":"UltralitePickerController"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"UltralitePickerController"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}