{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDisplayCell:"},{"text":"(","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":" *) ","kind":"text"},{"text":"cell","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}]}]}],"metadata":{"roleHeading":"Instance Method","title":"tableView:willDisplayCell:forRowAtIndexPath:","role":"symbol","externalID":"c:@CM@UltraliteSDK@objc(cs)UltralitePickerController(im)tableView:willDisplayCell:forRowAtIndexPath:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"symbolKind":"method","modules":[{"name":"UltraliteSDK"}],"navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/ultralitesdk\/ultralitepickercontroller\/tableview:willdisplaycell:forrowatindexpath:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/tableView:willDisplayCell:forRowAtIndexPath:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"]]},"sections":[],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController/tableView:willDisplayCell:forRowAtIndexPath:":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/tableView:willDisplayCell:forRowAtIndexPath:","title":"tableView:willDisplayCell:forRowAtIndexPath:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"role":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller\/tableview:willdisplaycell:forrowatindexpath:","kind":"symbol"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UltralitePickerController"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller","abstract":[{"text":"Convience UIViewController that can easily be shown to user to have them select a pair of glasses to communicate with.","type":"text"}],"title":"UltralitePickerController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UltralitePickerController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UltralitePickerController","op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/fragments","value":[{"text":"UltralitePickerController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/navigatorTitle","value":[{"text":"UltralitePickerController","kind":"identifier"}]}]}]}