{"metadata":{"externalID":"c:@M@UltraliteSDK@objc(cs)UltralitePickerController(py)title","modules":[{"name":"UltraliteSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"title","symbolKind":"property","fragments":[{"text":"title","kind":"identifier"}],"navigatorTitle":[{"text":"title","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitepickercontroller\/title"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/title","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"title"},{"text":";","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"]]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UltralitePickerController"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller","abstract":[{"text":"Convience UIViewController that can easily be shown to user to have them select a pair of glasses to communicate with.","type":"text"}],"title":"UltralitePickerController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UltralitePickerController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController/title":{"url":"\/documentation\/ultralitesdk\/ultralitepickercontroller\/title","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/title","abstract":[],"fragments":[{"text":"title","kind":"identifier"}],"kind":"symbol","type":"topic","title":"title","role":"symbol"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UltralitePickerController","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/title"},{"value":[{"text":"UltralitePickerController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/fragments"},{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/navigatorTitle","value":[{"text":"UltralitePickerController","kind":"identifier"}],"op":"replace"}]}]}