{"sections":[],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/viewWillDisappear:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"viewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitepickercontroller\/viewwilldisappear:"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@UltraliteSDK@objc(cs)UltralitePickerController(im)viewWillDisappear:","symbolKind":"method","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"UltraliteSDK"}],"title":"viewWillDisappear:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController/viewWillDisappear:":{"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"title":"viewWillDisappear:","kind":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller\/viewwilldisappear:","type":"topic","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController\/viewWillDisappear:","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltralitePickerController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UltralitePickerController"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ultralitesdk\/ultralitepickercontroller","abstract":[{"text":"Convience UIViewController that can easily be shown to user to have them select a pair of glasses to communicate with.","type":"text"}],"title":"UltralitePickerController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UltralitePickerController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltralitePickerController"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/title","op":"replace","value":"UltralitePickerController"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/fragments","value":[{"text":"UltralitePickerController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"UltralitePickerController"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltralitePickerController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}