{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/initWithCoder:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/initwithcoder:"]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@UltraliteSDK@objc(cs)UltraliteBaseViewController(im)initWithCoder:","title":"initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"UltraliteSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController":{"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller","navigatorTitle":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A convience base class that contains easily override points for starting control of ultralite, stop control, tap handler, on disconnect, on App leave, and showing the picker dialog."},{"type":"text","text":" "},{"text":"Just extend this and code away.","type":"text"}],"title":"UltraliteBaseViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UltraliteBaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController/initWithCoder:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/initwithcoder:","kind":"symbol","title":"initWithCoder:","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/initWithCoder:","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/title","value":"UltraliteBaseViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/fragments","value":[{"text":"UltraliteBaseViewController","kind":"identifier"}]},{"op":"replace","value":[{"text":"UltraliteBaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/navigatorTitle"}]}]}