{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppLeave"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/onappleave()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/onappleave()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/onAppLeave()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when application leaves the foreground"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppLeave"},{"kind":"text","text":"()"}],"title":"onAppLeave()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@UltraliteSDK@objc(cs)UltraliteBaseViewController(im)onAppLeave","modules":[{"name":"UltraliteSDK"}],"navigatorTitle":[{"kind":"identifier","text":"onAppLeave"}]},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"]]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController":{"role":"symbol","title":"UltraliteBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UltraliteBaseViewController"}],"abstract":[{"type":"text","text":"A convience base class that contains easily override points for starting control of ultralite, stop control, tap handler, on disconnect, on App leave, and showing the picker dialog."},{"type":"text","text":" "},{"type":"text","text":"Just extend this and code away."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController/onAppLeave()":{"role":"symbol","title":"onAppLeave()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppLeave"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when application leaves the foreground"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/onAppLeave()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAppLeave"}],"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/onappleave()"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"role":"collection","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","kind":"symbol","type":"topic","url":"\/documentation\/ultralitesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onAppLeave"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAppLeave"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onAppLeave"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/title","value":"UltraliteBaseViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/fragments","value":[{"kind":"identifier","text":"UltraliteBaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController~1onAppLeave()\/title","value":"onAppLeave"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController~1onAppLeave()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAppLeave"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}