{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPowerButtonTap"},{"kind":"text","text":"("},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"notification","content":[{"inlineContent":[{"type":"text","text":"Contains the notification with userInfo of "},{"code":"power_btn: <0 - off, 1 - on>","type":"codeVoice"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Called when the Ultralite power button is pushed. Abstract, override for your implementation.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"onPowerButtonTapWithNotification:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"UltraliteSDK"}],"title":"onPowerButtonTap(notification:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPowerButtonTap","kind":"identifier"},{"kind":"text","text":"("},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"externalID":"c:@M@UltraliteSDK@objc(cs)UltraliteBaseViewController(im)onPowerButtonTapWithNotification:","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/onPowerButtonTap(notification:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/onpowerbuttontap(notification:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/onpowerbuttontap(notification:)"]}],"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"]]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController":{"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller","navigatorTitle":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A convience base class that contains easily override points for starting control of ultralite, stop control, tap handler, on disconnect, on App leave, and showing the picker dialog."},{"type":"text","text":" "},{"text":"Just extend this and code away.","type":"text"}],"title":"UltraliteBaseViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UltraliteBaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController/onPowerButtonTap(notification:)":{"type":"topic","url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/onpowerbuttontap(notification:)","role":"symbol","title":"onPowerButtonTap(notification:)","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/onPowerButtonTap(notification:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onPowerButtonTapWithNotification:"}],"abstract":[{"text":"Called when the Ultralite power button is pushed. Abstract, override for your implementation.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPowerButtonTap"},{"kind":"text","text":"("},{"text":"notification","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"onPowerButtonTapWithNotification:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPowerButtonTapWithNotification:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onPowerButtonTapWithNotification:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"notification","content":[{"inlineContent":[{"text":"Contains the notification with userInfo of ","type":"text"},{"type":"codeVoice","code":"power_btn: <0 - off, 1 - on>"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"value":"UltraliteBaseViewController","op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/fragments","value":[{"kind":"identifier","text":"UltraliteBaseViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/navigatorTitle","value":[{"text":"UltraliteBaseViewController","kind":"identifier"}]},{"value":"onPowerButtonTapWithNotification:","op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController~1onPowerButtonTap(notification:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController~1onPowerButtonTap(notification:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPowerButtonTapWithNotification:","kind":"identifier"}]}]}]}