{"sections":[],"variants":[{"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/viewdidload"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/viewDidLoad","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad","role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"externalID":"c:@M@UltraliteSDK@objc(cs)UltraliteBaseViewController(im)viewDidLoad","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"UltraliteSDK"}]},"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController/viewDidLoad":{"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/viewDidLoad","type":"topic","url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/viewdidload","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"viewDidLoad","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController":{"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller","navigatorTitle":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A convience base class that contains easily override points for starting control of ultralite, stop control, tap handler, on disconnect, on App leave, and showing the picker dialog."},{"type":"text","text":" "},{"text":"Just extend this and code away.","type":"text"}],"title":"UltraliteBaseViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UltraliteBaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/title","op":"replace","value":"UltraliteBaseViewController"},{"op":"replace","value":[{"text":"UltraliteBaseViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/fragments"},{"value":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}