{"metadata":{"title":"viewDidAppear:","fragments":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"modules":[{"name":"UltraliteSDK"}],"externalID":"c:@M@UltraliteSDK@objc(cs)UltraliteBaseViewController(im)viewDidAppear:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/viewDidAppear:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/viewdidappear:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController":{"url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller","navigatorTitle":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A convience base class that contains easily override points for starting control of ultralite, stop control, tap handler, on disconnect, on App leave, and showing the picker dialog."},{"type":"text","text":" "},{"text":"Just extend this and code away.","type":"text"}],"title":"UltraliteBaseViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UltraliteBaseViewController","kind":"identifier"}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/UltraliteBaseViewController/viewDidAppear:":{"kind":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/UltraliteBaseViewController\/viewDidAppear:","url":"\/documentation\/ultralitesdk\/ultralitebaseviewcontroller\/viewdidappear:","role":"symbol","title":"viewDidAppear:","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/title","op":"replace","value":"UltraliteBaseViewController"},{"op":"replace","value":[{"kind":"identifier","text":"UltraliteBaseViewController"}],"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/fragments"},{"value":[{"text":"UltraliteBaseViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1UltraliteBaseViewController\/navigatorTitle"}]}]}