{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Property\/hashValue","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Property","doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Property\/RawRepresentable-Implementations"]]},"metadata":{"extendedModule":"Swift","roleHeading":"Instance Property","role":"symbol","title":"hashValue","symbolKind":"property","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::s:12UltraliteSDK0A0C8PropertyO","modules":[{"relatedModules":["Swift"],"name":"UltraliteSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ultralitesdk\/ultralite\/property\/hashvalue"]}],"references":{"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite":{"url":"\/documentation\/ultralitesdk\/ultralite","title":"Ultralite","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite","abstract":[{"type":"text","text":"Use this object to communicate with the glasses.  Handles all the communication to the BLE stack. Does all the protocol and encypting and decrypting of payloads."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Ultralite"}],"navigatorTitle":[{"kind":"identifier","text":"Ultralite"}],"kind":"symbol","type":"topic"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK":{"url":"\/documentation\/ultralitesdk","kind":"symbol","title":"UltraliteSDK","abstract":[{"type":"text","text":"Use this SDK to easily send text and images to your Vuxix smart glasses."}],"identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK","type":"topic","role":"collection"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/Property/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Property\/RawRepresentable-Implementations","url":"\/documentation\/ultralitesdk\/ultralite\/property\/rawrepresentable-implementations"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/Property":{"type":"topic","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Property","abstract":[{"type":"text","text":"Enum property’s that you can get and set on the ultralite"}],"kind":"symbol","url":"\/documentation\/ultralitesdk\/ultralite\/property","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Property"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Property"}],"title":"Ultralite.Property"},"doc://com.vuzix.UltraliteSDK/documentation/UltraliteSDK/Ultralite/Property/hashValue":{"type":"topic","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"abstract":[],"title":"hashValue","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","identifier":"doc:\/\/com.vuzix.UltraliteSDK\/documentation\/UltraliteSDK\/Ultralite\/Property\/hashValue","url":"\/documentation\/ultralitesdk\/ultralite\/property\/hashvalue"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/title","op":"replace","value":"Ultralite"},{"value":[{"kind":"identifier","text":"Ultralite"}],"op":"replace","path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/fragments"},{"path":"\/references\/doc:~1~1com.vuzix.UltraliteSDK~1documentation~1UltraliteSDK~1Ultralite\/navigatorTitle","value":[{"kind":"identifier","text":"Ultralite"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}